export const MessageType = {
    // 웹 페이지에서 컨텐츠 스크립트로 전달
    WEB_TO_CONTENT_SCRIPT_SUBMIT: 'WEB_TO_CONTENT_SCRIPT_SUBMIT',
    WEB_TO_CONTENT_SCRIPT_PROGRESS: 'WEB_TO_CONTENT_SCRIPT_PROGRESS',

    // 컨텐츠 스크립트에서 백그라운드로 전달
    CONTENT_SCRIPT_TO_BACKGROUND_SUBMIT: 'WEB_TO_CONTENT_SCRIPT_TO_BACKGROUND_SUBMIT',
    CONTENT_SCRIPT_TO_BACKGROUND_PROGRESS: 'WEB_TO_CONTENT_SCRIPT_TO_BACKGROUND_PROGRESS',

    // 백그라운드에서 새로운 컨텐츠 스크립트로 전달
    BACKGROUND_TO_NEW_CONTENT_SCRIPT_CHECK_LOGIN: 'BACKGROUND_TO_NEW_CONTENT_SCRIPT_CHECK_LOGIN',
    BACKGROUND_TO_NEW_CONTENT_SCRIPT_SUBMIT: 'BACKGROUND_TO_NEW_CONTENT_SCRIPT_SUBMIT',
    BACKGROUND_TO_NEW_CONTENT_SCRIPT_RESULT: 'BACKGROUND_TO_NEW_CONTENT_SCRIPT_RESULT',
    BACKGROUND_TO_NEW_CONTENT_SCRIPT_PROGRESS: 'BACKGROUND_TO_NEW_CONTENT_SCRIPT_PROGRESS',

    // 새로운 컨텐츠 스크립트에서 백그라운드로 전달
    NEW_CONTENT_SCRIPT_TO_BACKGROUND_SUBMIT: 'NEW_CONTENT_SCRIPT_TO_BACKGROUND_SUBMIT',
    NEW_CONTENT_SCRIPT_TO_BACKGROUND_PROGRESS: 'NEW_CONTENT_SCRIPT_TO_BACKGROUND_PROGRESS',
    NEW_CONTENT_SCRIPT_TO_BACKGROUND_RESULT: 'NEW_CONTENT_SCRIPT_TO_BACKGROUND_RESULT',
    NEW_CONTENT_SCRIPT_TO_BACKGROUND_CHECK_LOGIN: 'NEW_CONTENT_SCRIPT_TO_BACKGROUND_CHECK_LOGIN',
} as const;