export const MessageType = {
    SUBMIT: 'SUBMIT',
    CHECK_LOGIN: 'CHECK_LOGIN',
    RESULT: 'RESULT',
    EXECUTE: 'EXECUTE',
    REQUEST_PROGRESS: 'REQUEST_PROGRESS',
    RESPONSE_PROGRESS: 'RESPONSE_PROGRESS'
} as const;